name: Pabrik APK Nganjuk 2026 (Ultra Fast)

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Sedot Kode dari Repo Lo
      uses: actions/checkout@v4

    - name: Buka Resleting Kardus Nganjuk
      run: unzip nganjuk.zip

    - name: Siapin Mesin Java 21 
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Setup Gradle (Otomatis Paling Baru)
      uses: gradle/actions/setup-gradle@v3
      with:
        gradle-version: 'current'

    - name: Cari Pabrik & Rakit APK (Smart Radar)
      run: |
        PABRIK_DIR=$(dirname $(find . -name "settings.gradle" | head -n 1))
        echo "Wah Ketemu nih Pabriknya di: $PABRIK_DIR"
        cd $PABRIK_DIR
        gradle assembleDebug

    - name: Bungkus dan Kirim APK ke CEO
      uses: actions/upload-artifact@v4
      with:
        name: Markas-Nganjuk-2026-APK
        path: ./**/app/build/outputs/apk/debug/*.apk
