name: Pabrik APK Nganjuk 2026 (Ultra Fast)

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Sedot Kode dari Repo Lo
      uses: actions/checkout@v4

    - name: Buka Resleting Kardus Nganjuk (Presisi Tinggi)
      run: unzip nganjuk.zip # NAH INI DIA! FOKUS KE 1 FILE DOANG!

    - name: Siapin Mesin Java 21 (Syarat Wajib Gradle 9)
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Setup Gradle 9.1 (Mesin 2026)
      uses: gradle/actions/setup-gradle@v3
      with:
        gradle-version: '9.1'

    - name: Rakit APK Sekarang!
      working-directory: ./Pabrik-APK-Nganjuk
      run: gradle assembleDebug

    - name: Bungkus dan Kirim APK ke CEO
      uses: actions/upload-artifact@v4
      with:
        name: Markas-Nganjuk-2026-APK
        path: Pabrik-APK-Nganjuk/app/build/outputs/apk/debug/*.apk
