name: Pabrik APK Nganjuk

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Sedot Kode dari Repo Lo
      uses: actions/checkout@v4

    - name: Cek Isi Repo (Intelijen)
      run: ls -la

    - name: Buka Resleting Kardus ZIP (Sapu Jagat)
      run: unzip *.zip

    - name: Siapin Mesin Java (JDK 17)
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2

    - name: Rakit APK Sekarang!
      working-directory: ./Pabrik-APK-Nganjuk
      run: gradle assembleDebug

    - name: Bungkus dan Kirim APK ke CEO
      uses: actions/upload-artifact@v4
      with:
        name: Markas-Nganjuk-Pro-APK
        path: Pabrik-APK-Nganjuk/app/build/outputs/apk/debug/*.apk
        
